In [1]:
# Imports
from PIL import Image
from skimage import feature
import cv2
import glob, os
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Store the string entered in the variable directory
directory = raw_input('\nEnter the directory of the image database: ')


Enter the directory of the image database: Image


In [3]:
if not os.path.exists(directory):
    raise Exception('\nThe directory you entered does not exist')
else:    
    # 'Navigate' in the informed directory
    os.chdir(directory)
    print '\nCurrent Directory: ',os.getcwd()


Current Directory:  /home/alexandra/Desktop/Em Andamento/Image


In [4]:
def LBP_histograms_regions(path, use_circular_neighborhood=True):
    # Number of points
    P = 8
    
    # Radius
    R = 2
    
    # It receives a vector with 255 positions (0 to 255)
    bins = np.array(range(256))
    # print'\nBins:',bins

    # Opens a image
    img = Image.open(path)

    # Shows the width and height of the image and the color indexing mode
    print img.size, img.mode
    
    # Transforms the image into an array
    image = np.asarray(img)
    # print'\nImage array:',image
    
    # Regular mesh is 7x7 which gives us 49 regions, each region contains 18x18 pixels (window size)
    
    # Define Grid (k * K)
    k = 7
    
    # Define the Window size
    window_size_row = image.shape[0] / k
    window_size_column = image.shape[1] / k
    # print 'Window size row:',row
    # print 'Window size column:',column

    store_all = []
    count_region = 0

    # Scroll from the upper left corner of the image
    # 'Cutting' the window and calculating the LBP histogram
    # i = Intensity
    # r = Region
    for i in range(0, image.shape[0] - window_size_row, window_size_row):
        # Shows in which row of the region we are navigating (1 to 7)
        # Remember that each row occupies 7 rows
        print('\nWindow row: '+str(((i / window_size_row) + 1)))
        
        # With each row, runs 18 columns
        for r in range(0, image.shape[1] - window_size_column, window_size_column):
            # Shows in which column of the region we are navigating (1 to 7)
            # # Remember that each column occupies 7 columns
            print('\nWindow column: '+str(((r / window_size_column) + 1)))

            # Counters of regions
            count_region = count_region + 1
            
            # Region
            region = image[i:i + window_size_row, r:r + window_size_column]
            
            # Shows the 'cropped' region
            print('\nRegion: '+str(count_region))
            print region
            
            
            if use_circular_neighborhood:
                # Compute the LBP circular_neighborhood representation of the regions of each image,
                # and then use this to build the histogram
                
                # The uniform  method indicates that we are computing the rotation
                # and grayscale invariant form of LBPs.
                LBP = feature.local_binary_pattern(region, P, R, method="uniform")
                
                # Histogram
                (hist, _) = np.histogram(LBP, bins=np.arange(0, P + 3), range=(0, P + 2))
            else:
                # Histogram
                (hist, _) = np.histogram(region, bins=bins)
    
            # Shows the Histogram
            print '\nHistogram: '
            print hist
            
            # Join all n regions histograms of each image
            store_all.append(hist)
            
    # Shows
    print('\nAll n region histograms: '+str(store_all))
    
    return store_all

In [5]:
histogram_dictionary = {}

# Call the functions
for fn in glob.glob('*.jpg'):
    print '\nImage:',fn

    # Gets the file name without the extension
    f = glob.os.path.splitext(fn)[0]
    
    # If your images are already the result of the basic LBP operator (in this case), set the [variable] as False,
    # but if you want to take your images the LBP circular (P, R) neighborhood,set the [variable] as True
    histogram_dictionary["{0}".format(f)] = LBP_histograms_regions(path=fn,
                                                                   use_circular_neighborhood=False)


Image: 001.jpg
(128, 128) RGB

Window row: 1

Window column: 1

Region: 1
[[[ 39  39  39]
  [125 125 125]
  [163 163 163]
  [168 168 168]
  [114 114 114]
  [148 148 148]
  [136 136 136]
  [ 79  79  79]
  [100 100 100]
  [122 122 122]
  [124 124 124]
  [118 118 118]
  [141 141 141]
  [129 129 129]
  [128 128 128]
  [123 123 123]
  [ 83  83  83]
  [121 121 121]]

 [[ 96  96  96]
  [164 164 164]
  [166 166 166]
  [117 117 117]
  [113 113 113]
  [112 112 112]
  [ 91  91  91]
  [117 117 117]
  [126 126 126]
  [141 141 141]
  [143 143 143]
  [124 124 124]
  [140 140 140]
  [139 139 139]
  [141 141 141]
  [122 122 122]
  [118 118 118]
  [ 82  82  82]]

 [[159 159 159]
  [155 155 155]
  [107 107 107]
  [132 132 132]
  [ 75  75  75]
  [ 85  85  85]
  [124 124 124]
  [146 146 146]
  [160 160 160]
  [213 213 213]
  [154 154 154]
  [122 122 122]
  [129 129 129]
  [133 133 133]
  [153 153 153]
  [133 133 133]
  [125 125 125]
  [127 127 127]]

 [[165 165 165]
  [ 83  83  83]
  [139 139 139]
  [ 82 


Region: 10
[[[ 47  47  47]
  [123 123 123]
  [135 135 135]
  [159 159 159]
  [184 184 184]
  [189 189 189]
  [186 186 186]
  [ 78  78  78]
  [ 86  86  86]
  [ 85  85  85]
  [ 90  90  90]
  [106 106 106]
  [155 155 155]
  [196 196 196]
  [195 195 195]
  [114 114 114]
  [112 112 112]
  [107 107 107]]

 [[ 38  38  38]
  [124 124 124]
  [137 137 137]
  [163 163 163]
  [194 194 194]
  [211 211 211]
  [135 135 135]
  [ 92  92  92]
  [123 123 123]
  [113 113 113]
  [111 111 111]
  [118 118 118]
  [133 133 133]
  [121 121 121]
  [172 172 172]
  [139 139 139]
  [104 104 104]
  [125 125 125]]

 [[ 29  29  29]
  [ 95  95  95]
  [138 138 138]
  [164 164 164]
  [204 204 204]
  [215 215 215]
  [140 140 140]
  [194 194 194]
  [210 210 210]
  [195 195 195]
  [213 213 213]
  [226 226 226]
  [215 215 215]
  [191 191 191]
  [204 204 204]
  [222 222 222]
  [217 217 217]
  [223 223 223]]

 [[ 28  28  28]
  [ 53  53  53]
  [127 127 127]
  [158 158 158]
  [195 195 195]
  [195 195 195]
  [181 181 181]
  [222

[[[128 128 128]
  [133 133 133]
  [140 140 140]
  [129 129 129]
  [ 99  99  99]
  [112 112 112]
  [176 176 176]
  [226 226 226]
  [215 215 215]
  [162 162 162]
  [175 175 175]
  [153 153 153]
  [176 176 176]
  [170 170 170]
  [147 147 147]
  [108 108 108]
  [ 97  97  97]
  [117 117 117]]

 [[214 214 214]
  [201 201 201]
  [210 210 210]
  [223 223 223]
  [220 220 220]
  [194 194 194]
  [135 135 135]
  [190 190 190]
  [223 223 223]
  [180 180 180]
  [187 187 187]
  [157 157 157]
  [170 170 170]
  [174 174 174]
  [155 155 155]
  [112 112 112]
  [103 103 103]
  [117 117 117]]

 [[218 218 218]
  [200 200 200]
  [213 213 213]
  [225 225 225]
  [224 224 224]
  [206 206 206]
  [207 207 207]
  [174 174 174]
  [188 188 188]
  [204 204 204]
  [183 183 183]
  [152 152 152]
  [171 171 171]
  [183 183 183]
  [155 155 155]
  [101 101 101]
  [110 110 110]
  [102 102 102]]

 [[139 139 139]
  [126 126 126]
  [120 120 120]
  [146 146 146]
  [199 199 199]
  [221 221 221]
  [207 207 207]
  [164 164 164]
  

In [6]:
# Shows everything in the dictionary
# print histogram_dictionary

In [7]:
# Shows a specific key in the dictionary
# print histogram_dictionary['1NM']

In [8]:
# Shows the histogram of a specific region of a key in the dictionary (0 to 48)
# print histogram_dictionary['1NM'][48]

In [9]:
for key, value in histogram_dictionary.iteritems():
    # Extract all values from the dictionary
    # This means that the access variables is hist_ [key name]
    globals()['hist_%s' % key] = value
    
    # Shows only the key in the dictionary
    print key

001


In [10]:
# For example:
# print hist_2SM
# print hist_2SM[48]

In [11]:
# Vector of weights of each region

# Black 0.0
# Dark Grey 1.0
# Light Grey 2.0
# White 4.0

w = [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0,
     2.0, 4.0, 4.0, 1.0, 4.0, 4.0, 2.0,
     1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 
     0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0,
     0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0,
     0.0, 1.0, 1.0, 2.0, 1.0, 1.0, 0.0,
     0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]

In [12]:
def chi_square(histogram1, histogram2, weight):
    #Computes the chi-square distance between two histograms (or histogram sequences)

    x2w = 0
    store_all = []
    
    for i in range(0, histogram1.shape[0]):
        if histogram1[i] != histogram2[i]:
            x2w += weight * int(((histogram1[i] - histogram2[i])**2) / (histogram1[i] + histogram2[i]))
   
    # 49 x2w of each image
    store_all.append(x2w)
    
    return store_all

In [13]:
x2w_dictionary = {}

for region in range(0, 49):
    x2w_dictionary["{0}".format(region)] = chi_square(hist_2SM[region], hist_1SM[region], w[region])

NameError: name 'hist_2SM' is not defined

In [14]:
print x2w_dictionary

{}
